### ISSUE TITLE
Waterfox is unresponsive at startup

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#1221]
When I open waterfox on my pc it will be unresponsive when I start it up but then after a few minutes it becomes responsive.is this issue just me?

**Comment by grahamperrin** [comment]
Which version of Waterfox, exactly?

**Comment by ghost** [comment]
I’m on the latest version of waterfox

**Comment by troysjanda** [comment]
> I’m on the latest version of waterfox

There is two current latest version 2019.10 classic and 2019.10 current please when seeking help provide as much relevant information as possible.

**Comment by NebelNidas** [comment]
This also happens to me sometimes, on all versions of Waterfox 56. It may have something to do with session restoration as discussed in #905, though I'm not entirely sure.
When starting the browser, nothing in the website itself is usable; you can not click, scroll etc., nothing responds. Not even the cursor changes when hovering links. Waterfox itself is fine, though. The way I got the website to work again was just by resizing of my Waterfox window. After that, everything works again just fine.
I unfortunately can't give any further details as this also happens very rarely (once a month while opening Waterfox 10-20 times a day), next time it does I'll post additional info here.

**Comment by ghost** [comment]
im on waterfox 56 as well

**Comment by grahamperrin** [comment]
> waterfox 56

56.2.14 is outdated. 

Can you reproduce the issue with Waterfox Classic 2019.10? 

Use the installer at https://www.waterfox.net/releases/

**Comment by NebelNidas** [comment]
Oh, I thought it was just a rebranding of 56.2.14... But why doesn't Waterfox update to it?
Nevertheless, as said above, I think it's a session restoration problem and I don't think it's been fixed in 2019.10... As soon as it happens again I'll send the details.

**Comment by Squall-Leonhart** [comment]
as of just now, auto update does push the update.

**Comment by NebelNidas** [comment]
Yeah, now it works...

**Comment by grahamperrin** [comment]
> it works...

Responsive at startup, yes?

**Comment by ghost** [comment]
I updated to Waterfox Classic 2019.10 and I still have the same problem

**Comment by grahamperrin** [comment]
Please let us have troubleshooting information. 

Use the **Copy text to clipboard** button at: 

- about:support

**Comment by LL25255252** [comment]
@epicodertime take @grahamperrin advice and post the troubleshooting information.
It might be one of your addons that causes it.
I have 70 addons and got Waterfox Classic 2019.10  a few minutes ago. It seems to run as fast as the previous version. It takes 4 seconds to load and about 5 seconds more for the CPU to drop to its minimum (3% in Process Explorer)

**Comment by ghost** [comment]
Name | Waterfox
-- | --
56.2.14
20190902231505
Show Update History
release
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0 Waterfox/56.2.14
Windows_NT 10.0
Open Folder
about:plugins
about:buildconfig
about:memory
about:performance
about:serviceworkers
0/1 (Disabled by accessibility tools)
 
false (disabled by default)
Missing
Missing
false
about:profiles

**Comment by grahamperrin** [comment]
> 56.2.14

That is outdated. Please see https://github.com/MrAlex94/Waterfox/issues/1221#issuecomment-546195898 above and install the more recent release. 

### Hint

When you copy the troubleshooting information, use the **Copy text to clipboard** button.

**Comment by NebelNidas** [comment]
> 
> 
> > it works...
> 
> Responsive at startup, yes?

Sorry for the confusion, this was a response to @Squall-Leonhart's notice that auto update now works. And no, @LL25255252, it surely isn't related to addons. It has happened to me multiple times with fresh installs and the session restoration on startup enabled, that's why I think this is the cause.

**Comment by Squall-Leonhart** [comment]
if you are restoring a session, yes it till be non responsive for some time till the tabs contents are established and will depend on the amount of tabs.

**Comment by NebelNidas** [comment]
You mean while the tabs' properties are loaded from the safe file? Could be plausible, but everything had already been initialized when this bug occurred. Let's not speculate about possible causes until we have proper information.

**Comment by Squall-Leonhart** [comment]
no, im pretty sure about it since i've measured and profiled firefox startups across many versions.

even in multiprocess mode, the tabs properties, its favicon and title are restored, as well as a loose map to the state of the tab when it was unloaded, either manually or through restarting of the browser.

**Comment by grahamperrin** [comment]
@epicodertime thanks for the closure. 

In retrospect, would you describe the issue as transient?

**Comment by NebelNidas** [comment]
**[REQUESTING REOPENING]**

I finally got the error again and got it reproducible almost every time. I'm no Firefox expert, but let me explain what I think is going on:
1. Depending on your system's hardware, when loading Firefox with session restore on startup enabled, it sometimes doesn't load your extensions right away, which can for example lead to a website loading ads even when an adblocker is installed. This is reproducible especially when the selected tab is a heavy website. The affected addons get then loaded shortly after.
2. I haven't tested enough to know for sure, but somehow the website often becomes non-interactable right after, maybe caused by the now delayed loading of an addon. Perhaps caused by e10? Not tested yet.
3. By causing a reload of the rendering of the website, e.g. by shortly switching to another tab and back again or by pressing ALT to show the menu, everything is interactable again.

I don't know if @epicodertime had another issue, his description isn't explaining his problem good enough. Should I open a new issue for this?
Anyway, I doubt my profile which is reproducible for me will be for everyone of you. I'll look into it and post it here later, for now I can only give you this short recording: https://www.youtube.com/watch?v=HQqAeGyyLeo
As you can see, nothing is interactable, not even the scroll bar. Also, ads load even though ABP is installed, sign of delayed loading. You can also see that my cursor stays at the busy state indefinitely, until I moved it outside of the website container. The "heavy" website that worked for me here was a youtube video, which one shouldn't matter.

**Comment by ghost** [comment]
That was the issue I was talking about

**Comment by grahamperrin** [comment]
> … Firefox … doesn't load your extensions right away, …

Mozilla bug [1378459 - (webextensions-startup) [meta] Allow some addon functionality to load prior to any content loading](https://bugzilla.mozilla.org/show_bug.cgi?id=1378459)

@epicodertime if that's the underlying bug, then please consider prefixing the subject line of this issue #1221: 

`1378459 `
