### ISSUE TITLE
Current 2020.07.2 gets a broken Address bar if you remove the Home Page button from the toolbar

### ISSUE THREAD

**Issue by InvisibleManX** [MrAlex94/Waterfox#1711]
**Describe the bug**

(Tested with the top position of the toolbar only.)

Address bar doesn't work. 
If you type something there and hit Enter, it doesn't work. 
It also doesn't show address suggestions from history as you type anything there. 

If it somehow gets temporarily fixed, as soon as you restart a browser it gets broken again. 
If you create new windows it's broken in those windows.

It gets completely fixed only if you have a "Waterfox Home Page" button in front of the address bar inside your browser's toolbar.

**To Reproduce (if you don't have this bug)**

Remove the the "Waterfox Home Page" button from the toolbar. 

(Though if you won't be able to reproduce the bug this way, you should go to "Customize", hit "Restore Defaults" button there, and then remove that "Waterfox Home Page" button from the toolbar.)

Restart the browser.

Try to type inside the Address bar. No address suggestions from history would appear, and if you type some web address there and hit Enter, nothing will happen.

Try it in the current window, or try to create a new window (or a private window).

**My configuration** 
 - Device: PC
 - OS: Windows 7
 - Version: Current 2020.07.2

**Comment by hawkeye116477** [comment]
https://github.com/MrAlex94/Waterfox/issues/1175.

**Comment by Daviljoe193** [comment]
Happens to me too, and downgrading to 2020.07.1 (Only other version I had on my system) caused the address bar to work properly again.

**Comment by floral-qua-floral** [comment]
This looks remarkably similar to the recent search bar issue that was patched in this version, but with some small differences.

Similarities:
1. The field can hold text, but pressing enter has no effect
2. The issue can be temporarily resolved by open the Customize menu and then closing it. It will be fixed until the browser is restarted, at which point it will be broken again

Differences:
1. Pressing Ctrl-L to select the address bar works. Back when the search bar was broken, Ctrl-E would _not_ select the search bar.
2. The broken search bar did still offer search suggestions, however the broken address bar does not offer suggestions.

**Comment by RPYoshi** [comment]
![image](https://user-images.githubusercontent.com/6041818/90315044-33230980-dee6-11ea-926e-ad91b19038e7.png)

What to do? Search bar and address bar are switched and I can't move the search bar or remove it.

Changing the Options->Search->Search Bar settings does nothing.
Customize->Restore Defaults does nothing.

**Comment by hawkeye116477** [comment]
Download new version.

**Comment by RPYoshi** [comment]
![image](https://user-images.githubusercontent.com/6041818/90315164-35399800-dee7-11ea-806e-20c6264d7b64.png)

2.1?

**Comment by RPYoshi** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/6041818/90315164-35399800-dee7-11ea-806e-20c6264d7b64.png)
> 
> 2.1?

I was already running 2.1. I think it updated this morning for me.
Still isn't working.

**Comment by hawkeye116477** [comment]
Ok, so I don't know, I haven't that problem.

**Comment by RPYoshi** [comment]
Just did a full refresh of Waterfox config and things are working.

about:support->Refresh Waterfox Current

Thanks

**Comment by InvisibleManX** [comment]
@RPYoshi 
Apparently the whole refresh (with losing all the settings and addons) isn't necessary. 

I managed to fix all the issues caused by recent updates simply by removing the file "xulstore.json" from the user profile folder of the browser (while the browser was closed) and then opened my browser. Everything was fixed.

**Comment by RPYoshi** [comment]
Well for information (and git blame) here is the section of my xulstore.json file that contains the browser.xul info before the reset. I think clicking on Customize->RestoreDefaults should just delete the nav-bar object since my new xulstore.json doesn't even have that anymore.

**Backup before Restore**
*Modified: August ‎15, ‎2020, ‏‎11:52:18 AM*
```
  "chrome://browser/content/browser.xul": {
    "main-window": {
      "screenX": "-1732",
      "screenY": "17",
      "width": "1060",
      "height": "1041",
      "sizemode": "maximized"
    },
    "PersonalToolbar": {
      "collapsed": "true",
      "currentset": "personal-bookmarks"
    },
    "place:parent=menu________": {
      "open": "true"
    },
    "toolbar-menubar": {
      "currentset": "menubar-items,toolbar-menubar-pagetitle",
      "autohide": "true"
    },
    "TabsToolbar": {
      "currentset": "tabbrowser-tabs,new-tab-button,alltabs-button"
    },
    "nav-bar": {
      "currentset": "back-button,forward-button,stop-reload-button,home-button,urlbar-container,search-container,downloads-button,bookmarks-menu-button,library-button,https-everywhere-eff_eff_org-browser-action,support_lastpass_com-browser-action,ublock0_raymondhill_net-browser-action,_5caff8cc-3d2e-4110-a88a-003cc85b3858_-browser-action",
      "collapsed": "false"
    },
    "sidebar-box": {
      "sidebarcommand": "",
      "width": ""
    },
    "sidebar-title": {
      "value": ""
    }
  },
```

**New after restore and extensions install**
*Modified: ‎August ‎16, ‎2020, ‏‎9:07:27 AM*
```
"chrome://browser/content/browser.xul": {
    "main-window": {
      "screenX": "4",
      "screenY": "4",
      "width": "1296",
      "height": "1011",
      "sizemode": "maximized"
    },
    "sidebar-box": {
      "sidebarcommand": "",
      "width": ""
    },
    "sidebar-title": {
      "value": ""
    }
  },
```
