### ISSUE TITLE
Issues with Fox.com and other Sites.... 

### ISSUE THREAD

**Issue by A0R-R0CKS** [MrAlex94/Waterfox#1754]
When I go to Foxnews.com the Post Comments are no longer Showing but work in Chrome........ This is with Both Versions of Current Build of Waterfox. 2nd Issues is many form boxes on website are not visible have to keep clicking around to find them because the Boxes are not visible in both Current Versions of Waterfox and yet show in Chrome.... 

**To Reproduce**
 no error just does not load or show the Discussion Post options.... 

**Expected behavior**

on various sites fill out fields or boxes are invisible on my sites or the cursor is not aligned with the area to enter information 
Not using any Add-Ons........ 

**Screenshots**

**My configuration** 
 - Device:  PC 
 - OS:  Windows 10 Professional and on my Windows 7 Enterprise Laptop 
 - Version:  Classic 2020.08.1 (64-bit) and 2020.07.2.1 (64-bit)  Regular 64 Waterfox 

**Additional context**

**Comment by hawkeye116477** [comment]
Where comments should be? I didn't see them on https://www.foxnews.com/us/hurricane-sally-warning-gulf-coast-louisiana-mississippi-new-orleans-mandatory-evacuation-storm-surge, but same is on Vivaldi and Chromium, so it maybe something wrong with site.

**Comment by A0R-R0CKS** [comment]
Here is what I am talking About with Waterfox you dont see the comment area on the page ... 
![wf](https://user-images.githubusercontent.com/20975332/93130921-453cc700-f6a1-11ea-9d7b-5545327b217e.jpg)

With Chrome 
![ch](https://user-images.githubusercontent.com/20975332/93130965-584f9700-f6a1-11ea-88f6-010c3bd0a832.jpg)

you will notice it does show in Chrome ....

It use to work with Waterfox but now now the Comment area is invisible...............

**Comment by hawkeye116477** [comment]
> you will notice it does show in Chrome ....
> 
> It use to work with Waterfox but now now the Comment area is invisible...............

Comments are also not visible on Firefox and Chromium-based browsers. I guess that you are using cached version and probably if you'll cleanup cookies and cache then will be same situation as on Waterfox. Looks like that's problem with site/server, so webmaster should fix that.

**Comment by A0R-R0CKS** [comment]
It is Cleaned I am a former I.T. Tech Cleaning the Cache and Cookie / History does not fix it .... I am not gonna report it if  i was not cleaning everything................................

**Comment by hawkeye116477** [comment]
> Cleaning the Cache and Cookie / History does not fix it 

Seems that you didn't read properly or we didn't understand each other, I didn't told you that will fix that problem. I only told that when you clean browsing data on Chrome, then comments probably also will disappear on Chrome.

The other possibility is that comments are geo-locked, so I didn't see them, but that would be really weird and as I see errors on console on Chromium, then I suspect that's rather problem on website itself. Maybe they are doing some A/B testing, so it's possible also that on some browsers sometimes will be fine.

**Comment by tcreek** [comment]
I am seeing something similar. However, my view is a bit different. It is like the comment section is starting to load, but never does. It happened maybe two weeks ago, but then stopped. It is back again, but this time comment section is not loading anymore.

![waterfox](https://user-images.githubusercontent.com/4149717/93843647-266da000-fc60-11ea-9e19-7e7914e9558a.JPG)

**Comment by A0R-R0CKS** [comment]
Yep it wont load anymore on Water Fox Classic or Regular 
![Untiewwetled-1](https://user-images.githubusercontent.com/20975332/93846110-22964980-fc71-11ea-8649-f27d94794728.jpg)

**Comment by tcreek** [comment]
I just tried with Firefox 68.12.0 ESR

![Screenshot from 2020-09-22 06-29-16](https://user-images.githubusercontent.com/4149717/93876872-23dd6b80-fc9d-11ea-824c-3f83b5d37a5a.png)

It appears to be a Waterfox issue

**Comment by hawkeye116477** [comment]
So looks like that comments may be geolocked. Why they did that?

Did you have some error on browsers console (ctrl+shift+i and console tab)?

**Comment by tcreek** [comment]
> So looks like that comments may be geolocked. Why they did that?
> 
It is for sure not geolocked. Comments appear also in the Amazon Silk browser which is a fork of Chromium. I also have access to IP addresses in Mexico. Comments still appear in Firefox, and Silk

**Comment by A0R-R0CKS** [comment]
The site is not Geo Locked it is an issue with Waterfox you can open it in Edge, Firefox, and Google Chrome.... It use to work till a few weeks ago Waterfox nearly 3 weeks ago it stopped. The section of the page no longer will open with Waterfox it tries to open it but it keeps showing a Loading Box when you move your Mouse over the area of the page as shown in Screen Shot.  In any other Browser it opens immediately as the page is loaded.

**Comment by hawkeye116477** [comment]
@tcreek Ok, very weird, I tried to check now even with proxy and didn't see that comments on Waterfox and other browsers.

> it is an issue with Waterfox you can open it in Edge, Firefox, and Google Chrome

Maybe it looks that from your case, but I'll tell you again, I didn't see that comments even on other browsers than Waterfox, like Edge or Firefox, so some another problem maybe also on server side.

Anyway, did you have some error on browsers console (ctrl+shift+i and console tab)?

**Comment by A0R-R0CKS** [comment]
As you can see it shows that just fine in Chrome!!! Here is a Screen Shot taken just seconds ago in Chrome..... It loads in Firefox and Edge as well just fine... 
![FOX](https://user-images.githubusercontent.com/20975332/93928692-b6572c80-fce8-11ea-9920-96b22a39f71c.jpg)

**Comment by hawkeye116477** [comment]
@A0R-R0CKS I already saw that, but that doesn't change that unfortunately I don't have that on Waterfox and other browsers like Edge, so in my case it could be problem on server side. That could be also related with your problem, cuz maybe there are few versions of same page and maybe you got bad one only on Waterfox or problem is different than mine.

![Zrzut ekranu 2020-09-22 213839](https://user-images.githubusercontent.com/19818572/93929329-fe437700-fd1b-11ea-8ac9-a0666941d4ee.png) 

Anyway more important is rather answer for question - are you or @tcreek have some error now on browsers console (ctrl+shift+i and console tab) on Waterfox? Without much details I could only guess that's probably same issue as #1712.

**Comment by tcreek** [comment]
I now have the answer as to why Waterfox no longer functions on those sites

file:///home/trent/Pictures/Screenshot%20from%202020-10-19%2010-52-07.png

**Comment by tcreek** [comment]
Yep...Waterfox Classic is officially dead..I cannot even add images to here, nor even edit the previous message

**Comment by tcreek** [comment]
I am uploading this with GNOME's Web. Waterfox has serious issues now

![Screenshot from 2020-10-19 10-52-07](https://user-images.githubusercontent.com/4149717/96477734-79555b80-11fc-11eb-9207-8a0008a6ecb2.png)

**Comment by hawkeye116477** [comment]
I still didn't see that and don't have even that banner „celebrating America". I can only guess, maybe toggling `dom.webcomponents.enabled` or https://github.com/zakius/Polly/releases with chosen webcomponents-bundle.js will help. User-agent change probably will be also required.  

Anyway **what's error on console** (ctrl+shift+i, then console tab)?

**Comment by tcreek** [comment]
I just tried Waterfox (not classic) 202.09 and the comment section is now appearing. It is just on Classic we are now seeing the need to update browser. I guess Classic is about dead now.

**Comment by hawkeye116477** [comment]
@tcreek You still didn't reply about what I asked. What error you see on console? Is that workaround which I gave you works?

> I guess Classic is about dead now.

If problem is with webcomponents, then that might appear some time in Classic. Anyway unfortunately I don't know what's the problem with fox site, cuz seems they are somehow blocking comments section for me, cuz I didn't see that on all browsers (I see comments icon on top only).

**Comment by tcreek** [comment]
Errors from where?

From this page? 
![Screenshot from 2020-10-21 10-21-52](https://user-images.githubusercontent.com/4149717/96741585-92d6de80-1387-11eb-9820-70397081c6e8.png)

There are NONE. The above image is from Waterfox Classic trying to access that menu item. Console shows no error.

You can thumbs down all you want, but don't change the fact Waterfox Classic is about dead as all the other people are starting to report now with problems it is having, including the examples I have posted here recently

**Comment by hawkeye116477** [comment]
@tcreek Errors from fox site.

> starting to report now with problems it is having

It always had some problems with websites, it's nothing new. Same is in case of Pale Moon/Basilisk, but some problems are solved in future updates. Unfortunately it's not Firefox.

**Comment by tcreek** [comment]
There are no more errors on the Fox site. It clearly states they do not support the version of the browser we are using from the image I posted

**Comment by hawkeye116477** [comment]
> There are no more errors on the Fox site.

@tcreek Ok, I'll specify more, change user-agent to `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0`, then Ctrl+shift+i and console tab and go to fox site and see what will show.

Alternatively after user-agent change you can also try:

Install https://github.com/zakius/Polly/releases and choose webcomponents-bundle.js and see if it helps.

I already wrote that few posts ago, but seems you just ignored that and instead wrote not very helpful information... 

Sorry, but unfortunately, my glass ball broke.

>  It clearly states they do not support the version of the browser we are using from the image I posted

It's not clear, nothing says why this is so. Probably something can be done to fix that, but I need more helpful information :smile:. Does user-agent changing and using Polly helps?

**Comment by A0R-R0CKS** [comment]
To clarify things and so people dont get agitated Originally Firefox Classic worked fine on Foxnews.... When I posted the issue it just stopped and was not loading the Discussion Forum area. Then about a week ago it all of a sudden was working fine once again. Then a few days ago they just started showing the Your Browser is out dated if your using WaterFox Classic....  So perhaps that now makes things clearer to everyone.   

I use Classic as my preferred over the Regular Waterfox 64 because some classic plugins I use don't seem to work too well with the Regular version of  Waterfox.  

My Cable TV / Internet Provider has an issue with Waterfox Classic as well when I am watching my Cable TV stations online on Via Com owned channels the stations in HD wont load and says a unsupported Firefox as well...  They filtered that to only on the Via Com Stations, VHI, MTV, CMT, Paramont, and a few others. With that all other Stations play perfectly....

**Comment by tcreek** [comment]
> 
> 
> > There are no more errors on the Fox site.
> 
> @tcreek Ok, I'll specify more, change user-agent to `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0`, then Ctrl+shift+i and console tab and go to fox site and see what will show.
> 
> Alternatively after user-agent change you can also try:
> 
> Install https://github.com/zakius/Polly/releases and choose webcomponents-bundle.js and see if it helps.
> 
> I already wrote that few posts ago, but seems you just ignored that and instead wrote not very helpful information...
> 
> Sorry, but unfortunately, my glass ball broke.
> 
> > It clearly states they do not support the version of the browser we are using from the image I posted
> 
> It's not clear, nothing says why this is so. Probably something can be done to fix that, but I need more helpful information 😄. Does user-agent changing and using Polly helps?

It is VERY clear why as it even states YOUR BROWSER VERSION IS NO LONGER SUPPORTED.

Also that Polly does not even display correctly in Classic Waterfox

![2020-10-29 (2)](https://user-images.githubusercontent.com/4149717/97636427-b7bdf800-19fe-11eb-8f5a-6bce517bbe9c.png)

Also, how do we change user agent? Everything I find is for the newer Firefox

**Comment by tcreek** [comment]
Add another site:

kaggle.com no longer functions. It just keeps reloading without displaying anything. I am not seeing any errors in the console, though it keeps reloading
