### ISSUE TITLE
Several cosmetic issues on G4. Please fix.

### ISSUE THREAD

**Issue by Peacock365** [MrAlex94/Waterfox#2279]
### What happened?

Waterfox G4.0.0b1, macOS Big Sur 11.6

@adamp01 @MrAlex94 

I found several cosmetic issues on G4 that need addressing before anything is released.

- Waterfox Lepton: The loudness indicator is broken in the tab where any video / audio plays. Try it with any YouTube video and you shall see.
- Waterfox's settings still contain several greyed out items that need to be removed, mainly on about:preferences#general and on about:preferences#home
- about:protections still advertises various Mozilla services. I have already criticized this for G3, please remove these ads.
- Several of the settings of @hawkeye116477 are still missing.

Minor nitpicks / wishes:

- Why aren't Lepton Light and Lepton Dark specifically selectable? Why only according to the system theme?
- Whatever happened to the Australis-inspired themes of G3, please reintroduce those (maybe in a later release).

Thank you for your attention.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

macOS

**Comment by adamp01** [comment]
Thanks @Peacock365 - I'll be sorting out all the about:preferences related stuff today.

**Comment by Peacock365** [comment]
@adamp01 

Thanks for the quick reply the loudness indicator graphical issue especially drives me mad though.

**Comment by adamp01** [comment]
@Peacock365 

Would you be able to highlight what you are seeing vs. what you expect please? I was quickly comparing G3 with G4 and couldn't spot a difference - if you have some screenshots that'll help me pick up on what I'm missing

**Comment by Peacock365** [comment]
@adamp01 

1. Set Waterfox Lepton as your theme.
2. Go to any YouTube video.
3. Look at the tab the video plays in. 
4. Success.

**Comment by Peacock365** [comment]
@adamp01 

To be clear, when the Waterfox Lepton theme is used, is the loudness indicator meant to sit at the top right of the tab's favicon when a video plays within that tab? Because it sure as hell looks broken.

**Comment by adamp01** [comment]
@Peacock365 

This is the intention of the theme creator, yes. The reason for this is due to Mozilla updating where the Mute Tab overlay is rendered, thus making it impossible to do much with just css. If you take a look here: https://searchfox.org/mozilla-central/source/browser/base/content/tabbrowser-tab.js#23
The tab-icon-overlay is the class that the Mute Tab overlay falls into. It would be possible to amend this and move that line down to just above the tab-close-button on line 39, but that would break the Proton theme for users who prefer that (and probably give us some merge conflicts when pulling from Firefox at some point). 
Whilst I do agree the overlap of the overlay and the favicon isn't the most appealing of things, I think it is still preferable to how Proton handles things:
<img width="90" alt="image" src="https://user-images.githubusercontent.com/47503375/135865097-7024b6c0-904e-4162-a6e0-53a2c34feb94.png"><img width="89" alt="image" src="https://user-images.githubusercontent.com/47503375/135865134-ef4a5276-150b-40fe-bbf9-3e56d1c4a8a5.png">
Vs. Lepton: 
<img width="96" alt="image" src="https://user-images.githubusercontent.com/47503375/135865234-efa7e0c3-ec01-436f-9f01-b6ed0472bca4.png">

**Comment by Peacock365** [comment]
@adamp01 

So, in effect, this is not a bug, but a feature? No offense, but that looks horrible. Really, it does. Two possible fixes:

- When a video plays, replace the favicon of the tab with the loudness indicator, as is the case already with Proton.

**OR**

- Move the loudness indicator to the left of, and in immediate proximity to, the close button.

The way it looks now, it seems like a bug. Again, no offense, I like the rest of the theme as it is.

**Comment by adamp01** [comment]
@Peacock365 

I might add in an option to change how it looks at some point, but it's not at the top of the priority list right now.

**Comment by Peacock365** [comment]
@adamp01 

I have found several other issues as well, in addition to the ones already mentioned:

- Tracking protection doesn't seem to work at all. No matter on which website. It seems like Waterfox no longer connects to the Shavar domain (Have you removed it in the config?) from which Firefox receives its list updates. Please fix.
- When a light theme is used, including the bundled ones, the "Waterfox" text on the New Tab Page appears white-on-white and is thus hardly readable. Dark themes are OK.
- In the Chrome Web Store, the "Add to Waterfox" button only appears upon reload.
- In the Chrome Web Store and the Opera Store, trying to add any extension results in "undefined - This add-on could not be installed because it has not been verified" - Are you sure the disabling extension signing (xpinstall.signatures.required) has actually worked?
- On the Mozilla add-ons website, probably due to the different user agent, "Install Firefox" appears on every add-on page instead of "Add to Firefox".

**Comment by adamp01** [comment]
@Peacock365 

Thanks for all this - I'll action all of these.

**Comment by adamp01** [comment]
So this thread is up to date:

Tracking protection should be resolved with this: https://github.com/WaterfoxCo/Waterfox/commit/cd8b58d31eb673674be27b4bc82b6d72056eda92
Signature required issue should be resolved with this: https://github.com/WaterfoxCo/Waterfox/commit/fdb9a7ebc7b7dc459634e098f33acf128bbff3c8
Chrome web store issue should be resolved with this: https://github.com/WaterfoxCo/Waterfox/pull/2305

**Comment by MrAlex94** [comment]
https://github.com/WaterfoxCo/Waterfox/commit/6391c21385e5ad6982dd1231ed64191342a84164

This should be the last of the issues resolved. 

I'll close this unless you think there's anything unresolved.

**Comment by Peacock365** [comment]
Here is another few issues I have found, but not sure if they are bugs (as of Waterfox G4.0.0b2):

- For some extensions in the Chrome Web Store and Opera Store, when you try to add them, the following text appears: "This add-on could not be installed because not all of its features are supported". Here are two examples (just for reference):

https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn

https://addons.opera.com/en/extensions/details/ublock/

Now, I am not sure whether or not Waterfox is genuinely missing certain APIs or if these extensions just don't recognize existing APIs. So not sure if this is a bug or not.

- There seems to be a bug with the settings, go to about:preferences#home, reload the page. The "Recent Activity" section vanishes and curiously, the "Recent Activity" section on about:newtab also goes away despite "Recent Activity" being enabled under the clogwheel icon on about:newtab.
- Perhaps connected to the settings bug above: Go to about:preferences#home, reload the page and get the bug described above, then switch to about:preferences#general, there you'll get duplicate settings all of a sudden (same settings appear twice), this seems to only affect the "hawkeye" settings added by @adamp01 and not the preexisting Firefox settings.
- hawkeye's WebRTC, referrer header, geolocation settings are still missing under about:preferences#privacy
- I noticed that Waterfox does not display add-on version numbers on about:addons, please add this back. It suuuuuuucks without version numbers, you see.
- Waterfox still connects to firefox.settings.services.mozilla.com all the time... Are you sure that there is no way to fix this at the code level?
- Don't forget to purge the system add-ons. I think "DoH Roll-Out 2.0.0" should not exist in Waterfox. I would not hijack users in the same way Mozilla does. If someone wants DoH, the settings are there. If not, leave the user alone.
- Still unresolved: about:protections still advertises various Mozilla services. I have already criticized this for G3, please remove these ads

@MrAlex94, please reopen the issue for the time being. Thank you.

**Comment by adamp01** [comment]
@Peacock365 
I'll get back on the about:preferences stuff and fix it in the React code instead, that should solve those issues.
Thanks for pointing out the other missing settings as well.
I'll also take a look at the telemetry stuff with some urgency.

The rest I'll make a note of but will just go into general prioritisation.

**Comment by Peacock365** [comment]
To be honest, all the things I mentioned are probably high priority. If they were not, I would not have mentioned them specifically. Good to hear that at least some of them will be fixed ASAP.

**Comment by MrAlex94** [comment]
> For some extensions in the Chrome Web Store and Opera Store, when you try to add them, the following text appears: "This add-on could not be installed because not all of its features are supported". Here are two examples 

That's because Firefox doesn't support every WebExtension API.

> Waterfox still connects to firefox.settings.services.mozilla.com all the time... Are you sure that there is no way to fix this at the code level?

Yes, even Tor still keeps these connections.

> Please don't forget the scheduled telemetry task on Windows, please disable at build level: https://www.ghacks.net/2020/04/09/mozilla-installs-scheduled-telemetry-task-on-windows-with-firefox-75/

[This is already disabled](https://github.com/WaterfoxCo/Waterfox/blob/current/.mozconfig-x86_64-pc-windows-msvc#L41).

**Comment by Peacock365** [comment]
> That's because Firefox doesn't support every WebExtension API.

Are you sure about that? I am even getting this for extensions that I was able to add to Waterfox G3. And the overall number of extensions for which this message appears is very high, too.

> Yes, even Tor still keeps these connections.

Was there any specific reason why or were they just not able to remove it? Genuinely curious here.

> This is already disabled.

Ah, OK. Thanks. I've edited my comment above as well to reflect this.

**Comment by Peacock365** [comment]
@MrAlex94 

Is this a potential fix for firefox.settings.services.mozilla.com ?

https://wiki.archlinux.org/title/Firefox/Privacy#Editing_the_contents_of_omni.ja

**Comment by MrAlex94** [comment]
> Are you sure about that? I am even getting this for extensions that I was able to add to Waterfox G3. And the overall number of extensions for which this message appears is very high, too.

Yes I'm sure. If you have examples of ones that work on G3 and don't on G4, let us know.

> Was there any specific reason why or were they just not able to remove it? Genuinely curious here.
> Is this a potential fix for firefox.settings.services.mozilla.com ?

What that guide suggests is a terrible idea. The browser will output a bunch of noise complaining about lack of connections and it _does_ break things when it can't access those JSON dumps. It's used for everything from HSTS pinning to addon blocklists.

**Comment by Peacock365** [comment]
> What that guide suggests is a terrible idea. The browser will output a bunch of noise complaining about lack of connections and it does break things when it can't access those JSON dumps. It's used for everything from HSTS pinning to addon blocklists.

OK, fine. I relent. There seem to be good reasons for why this connection was kept then.

**Comment by black7375** [comment]
Hello? I am the author of [Lepton Theme](https://github.com/black7375/Firefox-UI-Fix).

I came across it by chance while doing a search.
I'm happy to be able to make a small contribution from a fork as old as Waterfox.

---

>  Whilst I do agree the overlap of the overlay and the favicon isn't the most appealing of things, I think it is still preferable to how Proton handles things:

Let me explain the intent when determining the overlay location.
In the case of the general tab, I was thinking of placing it right behind the favicon like Edge. 
However, it has the current design for the following reasons.
- Consistency: I wanted similar usage for both fixed tabs and normal tabs. UX consideration for muscle memory.
- Padding: I wanted to show as much information as possible within the limited tab space.

And here's why I removed the label.
- Language: English supports labels, but some languages ​​do not. So, I removed all the labels and made them expressed as icons (sound, PIP).


> ![](https://user-images.githubusercontent.com/47503375/135865234-efa7e0c3-ec01-436f-9f01-b6ed0472bca4.png)

The sound icon in the screenshot should be raised by about `3.5px` to cover less of the favicon.
It worked correctly in 1.0.0, but I think there was a mistake in the recent version while refactoring.
Fortunately, a [bug report](https://github.com/black7375/Firefox-UI-Fix/issues/249) has arrived and has been fixed in the latest version released recently.
https://github.com/black7375/Firefox-UI-Fix/releases/tag/v4.2.2

> Why aren't Lepton Light and Lepton Dark specifically selectable? Why only according to the system theme?

I'm making it, but the lepton is pretty complex.
Looking inside, it is divided into the following modes:
- System Default Theme:
  -  Windows7 dedicated theme
  - GTK, Windows10 accent color support
  - (Dev branch) Win10, Mac's dedicated theme
- Light weight Theme
  - Built-In Light Theme: Enhances contrast.
  - When Dark Mode: Apply dark mode to some content.
 
Therefore, it may take some time to provide the theme. 
Anyway, it would be cool if you could see system default, light and dark mode.
If waterfox maintainer or developers ever need my help, I can give you some advice.

---

I'm very excited to meet my project at Waterfox, thank you again.

**Comment by MrAlex94** [comment]
@black7375, thank you for the informative post! It is a great theme which is why it has been set as default 👍

> Why aren't Lepton Light and Lepton Dark specifically selectable? Why only according to the system theme?

This is more related to Waterfox - and will be coming in a future update.

If we can help in any way with the themeing do let us know!

**Comment by Peacock365** [comment]
Additional issues I have found:

- under about:license, the following text appears at the top of the page: _"Binaries of this product have been made available to you by the Mozilla Project under the Mozilla Public License 2.0 (MPL). Know your rights."_ Please change to "Waterfox Limited".
- When the Waterfox Australis Light theme is used, the tabs are hardly visible. Please give them a darker shade.

**Comment by Peacock365** [comment]
@adamp01 

Please react to my prior comment, the previous two issues still persist as of Waterfox G4.0.3.1

Additionally, I have found the following issues:

- When Waterfox is maximized (green maximize button at the top left of the window) under macOS, the tabs are moved to the right quite a bit. The last version of Waterfox with correct behavior was Waterfox G4.0.2.1.
- Google search suggestions don't work.
- When the Australis theme is used, the close / minimize / maximize button are moved from their normal position on macOS.

**Comment by adamp01** [comment]
@Peacock365 

- I'll sort the license now.
- I'll also sort the Australis Light tab colour as it's a super quick fix. I'll also see if I can quickly fix up the moving close etc. buttons.
- I've added Google search suggestions onto the backlog as will need a bit of investigative work.
- For the tab movement when maximized issue, could you send me a screenshot? It all seems OK for the Mac installations I've tested, but if I see the issue I may be able to implement something to fix. Might also be handy if you could show me the elements around it in Tools -> Browser Tools -> Browser Toolbox.

**Comment by Peacock365** [comment]
@adamp01 

I just wanted to ask: What is the status of add-on version number restoration in about:addons? Seeing the current version number would be handy since it makes updates more visible and may help when resolving add-on issues here. It seems like a trivial(?) fix to add this back, **please make this a priority**. 

I have found two further issues (Waterfox G4.0.8):

- In the Chrome Web Store, trying to add some extensions now triggers a download window for the CRX file. This should not happen, either the user gets notified when an API is missing or the extension should get added. Downloading the CRX file is not a possible outcome. Some random examples of extensions where this happens: https://chrome.google.com/webstore/detail/twitch-fullscreen-plus/jbbmdehmiclndmeedcocofcjlpgjnmea and https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh

- In the Opera Store, the "Add to Waterfox" button is rendered incorrectly when trying to add any extension.

Further wish list:

- Is there a reason why the Edge extension store is not supported? https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home

**Comment by adamp01** [comment]
@Peacock365 - I'll look into the addon version number today.

Thanks for raising those issues with the addon store compatability piece, I'll take a look at this as well.

We haven't had as much capacity as we had hoped for so this hasn't been getting as much attention as it needs, as such we don't have the time currently to look into expanding to Edge. Our priority would be introducing compatability for externally_connectable to improve the amounts of addons compatible with Waterfox.

**Comment by adamp01** [comment]
@Peacock365  - For the addon version number, it is displayed on the card detail like below:
<img width="687" alt="image" src="https://user-images.githubusercontent.com/47503375/157225795-dc026d57-803d-4505-b860-25744ec4a86f.png">

That should be sufficient no? Or are there cases you have seen where this is not being displayed?

**Comment by Peacock365** [comment]
@adamp01 

No, I mean the add-on version number in the add-on list, directly in about:addons (list view of all extensions). Waterfox Classic had it, Waterfox G3 had it, Waterfox G4 doesn't. You patched it back in in Waterfox G3 as well I recall. Having the add-on version number directly in the list view is better than what we have now because 1) updates are immediately visible from the list view, no need to click through all extensions to see if and when anything has been updated and 2) it makes troubleshooting easier because users are more likely to post the version number of the add-on if it is outright displayed in the list view. I mean, minimalism has its benefits, but Mozilla has been taking it a step too far here, please patch the add-on version number in the list view of all add-ons back in. Should not be hard to do. You also list this as an unresolved issue on your website btw:

https://www.waterfox.net/docs/releases/G4.0.8

I have found one further issue: 

- When in a hotel or in public places or public transport, Waterfox can fail to connect to public WiFi hotspots. Source: It failed on me, Firefox worked. This is caused by you developers disabling _network.captive-portal-service.enabled_ in the Waterfox-specific about:config preferences. Please remove this setting from the Waterfox-specific settings (000-waterfox.js), as it breaks Waterfox's ability to detect and connect to public WiFis.

**Comment by adamp01** [comment]
@Peacock365  - gotcha, I'm PR'ing something to make it look like this:
<img width="698" alt="image" src="https://user-images.githubusercontent.com/47503375/157431075-5e8df5d2-3f96-4dce-9c84-a990c4e1eba9.png">

I'll speak to Alex about flipping `network.captive-portal-service.enabled` as well.

Also, I did take a look at the addon stores stuff yesterday and I've noticed that sometimes the content handler picks up the `x-chrome-extension` type and attempts to install the addon correctly, and other times (seemingly at random) it won't and attempts to download it. Might take a minute to figure out what the root cause is here, as profiling was rather unhelpful.

I also didn't notice any rendering issues on the Opera web store, could you give me some additional details around what you are seeing?

**Comment by Peacock365** [comment]
@adamp01 

Thanks for fixing / investigating all mentioned issues here. Well done.

Opera Store issue: There is an "Add to Waterfox" green button at the top right of every extension page, e.g. here: https://addons.opera.com/extensions/details/ublock/
This button is enlarged / being rendered wrongly here. Can you confirm this?

**Comment by adamp01** [comment]
Looks like this for me, which is how it was intended:
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/47503375/157436586-61e73487-3d30-409f-83bd-6594ea82055d.png">

**Comment by Peacock365** [comment]
@adamp01 

Ah OK, the "Add to Waterfox" green button is much more enlarged for me. Since you can't reproduce the issue (I agree, your picture is as it should look), then I guess it is an issue with my profile. So consider this issue RESOLVED.

**Comment by Peacock365** [comment]
@adamp01 

Next to the _network.captive-portal-service.enabled_ issue, I noticed that we still do not have feature parity with Waterfox G3. Waterfox G3 supported NPAPI plug-ins, this support is gone aside from the bundled ones. Can you somehow make Waterfox detect plug-ins like Adobe Flash again? Is that a trivial fix?

**Comment by Peacock365** [comment]
@adamp01 

Is there any possibility of an NPAPI fix? Would be great if that were possible, but I have no idea how trivial or non-trivial that would be. I've seen that you have fixed the Chrome Web Store issue, thanks for this!

**Comment by adamp01** [comment]
@Peacock365 - I'll chat with Alex and try to gauge how hard the NPAPI piece would be. 

I appreciate you consistently raising things you find here as it's led to quite a few improvements and fixes, so wanted to quickly say thanks for that. If i miss anything as well let me know.

**Comment by s8wc3** [comment]
As of version 4.0.8 when using the Lepton theme the titlebar is painted in grey and doesn't respect the system's titlebar colour.
Windows 7 shown for effect (looks the worst), issue persists regardless of Windows version.
OK:
![2022-03-29_02-25-13](https://user-images.githubusercontent.com/60030618/160439423-c9c587e4-a4d4-419c-b14f-6724707c9fa3.png)
Scuffed:
![2022-03-29_02-25-46](https://user-images.githubusercontent.com/60030618/160439430-a81e1ae4-5c60-4c1d-ad4b-029668248d85.png)
@black3735 is this a known issue with the lepton theme?

**Comment by black7375** [comment]
I'll test it tomorrow.

**Comment by black7375** [comment]
- with Pure firefox: Works well

![image](https://user-images.githubusercontent.com/25581533/160610663-2afd04aa-7462-486d-abdc-8ae06ed6e3f1.png)

- Waterfox 4.0.8
![image](https://user-images.githubusercontent.com/25581533/160617074-81b8369a-4988-41a2-819c-8257773ab36d.png)

---

https://www.waterfox.net/docs/releases/G4.0.8

It will be one of two effect.

✨ New
-  Added a toggle on about:preferences to force light/dark mode with Lepton theme.

✔ Fixed
- Forcing dark mode in Lepton with `ui.systemUsesDarkTheme` on Linux distros should now work.

---

The system theme is applied only when `:root:not(:-moz-lwtheme)`, and it seems that the light weight theme is forcibly specified.

**Comment by Peacock365** [comment]
@MrAlex94 @adamp01 

As of Waterfox G5.0b2, I have found three issues:

- Under about:preferences#general, at the bottom of the page, extension and feature recommendation setting is still present albeit greyed out. Please remove.
- Waterfox G5 still has the DoH Rollout system add-on installed, you can see this under about:support. This is problematic because it hijacks the chosen DNS provider of the user. This had been fixed under Waterfox G4 via https://github.com/WaterfoxCo/Waterfox/commit/c48cfc81c4aa23ee7ccb6ccc5ab22e95fb94ac5b
- The commit https://github.com/WaterfoxCo/Waterfox/commit/b61298d8a4a3442a13fce39d9b838e397439b803 misses several changed settings compared to https://github.com/WaterfoxCo/Waterfox/commit/8b4a3fb42e682ecbc4e998bfab7904ed80906f8f minus _security.secure_connection_icon_color_gray_ as that one no longer works in G5.

Please fix these issues before pushing out the final build. Thank you.

**Comment by Peacock365** [comment]
@MrAlex94 @adamp01 

The issues still persist as of Waterfox G5.0b4, and so does the connectivity issue with public WiFi hotspots due to how you set _network.captive-portal-service.enabled_, please respond if you have noticed this new bug report.

**Comment by adamp01** [comment]
Thanks @Peacock365 - I have seen this and will be doing some PRs to achieve parity.

**Comment by adamp01** [comment]
I have done a PR to remove the greyed out options in `about:preferences#general`.

For DoH add-on, this is actually just left in to reduce headaches from merge conflicts when we pull from upstream. The addon itself is a basically blank manifest and doesn't do anything as here: https://github.com/WaterfoxCo/Waterfox/blob/future/browser/extensions/doh-rollout/manifest.json

Will check over prefs again, but I believe all the relevant ones have been captured, they are not all in the commit that you linked to.

**Comment by Peacock365** [comment]
@adamp01 

I see what you say about the DoH system add-on, understood. 

> Will check over prefs again, but I believe all the relevant ones have been captured, they are not all in the commit that you linked to.

Unfortunately, you are still missing the following prefs (all locked):

_browser.urlbar.speculativeConnect.enabled_ to **false**

_browser.xul.error_pages.expert_bad_cert_ to **true**

_extensions.experiments.enabled_ to **true**

Enabling pref sync was a good idea; I would also suggest the following sync prefs changed, this is all the nonsense left I think:

_services.sync.prefs.sync.browser.newtabpage.activity-stream.section.highlights.includePocket_ to **false**

_services.sync.prefs.sync.browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons_ to **false**

_services.sync.prefs.sync.browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features_ to **false**

_services.sync.prefs.sync.browser.newtabpage.activity-stream.feeds.section.topstories_ to **false**

_services.sync.prefs.sync.browser.discovery.enabled_ to **false**

_services.sync.prefs.sync.browser.crashReports.unsubmittedCheck.autoSubmit2_ to **false**

_services.sync.prefs.sync.app.shield.optoutstudies.enabled_ to **false**

_services.sync.prefs.sync.browser.newtabpage.activity-stream.section.topstories.rows_ to **false**

I also suggest enabling the search bar by default (not locked):

_browser.search.widget.inNavBar_ to **true**

And yeah, there is still the _network.captive-portal-service.enabled_ that has not been tackled for ages now and causes the browser to behave in unexpected ways when connected to a public WiFi.

Last but not least, I am missing the Proton default theme of Firefox, why do you consider Lepton the one and only now? I think this should be up to the user to decide. The Australis themes are also missing, however I always considered them to be subpar; here is perhaps a better approach you could look at: https://github.com/wilfredwee/photon-australis

**Comment by Peacock365** [comment]
@adamp01 @MrAlex94 

Adam, have you noticed my recent post? Please reply if you have noticed.

I slowly begin to be frustrated by Waterfox, more specifically its major releases. There always seem to be regressions that have already been patched in earlier Waterfox versions, and a lack of feature and settings parity. The way you reapply patches over and over again yet missing stuff every single time is highly frustrating, no idea how LibreWolf does it but they seem to be way more consistent across releases (and they actually rebase on major Firefox releases quite frequently). Whatever you do there is chaotic and desperately needs streamlining @Waterfox devs.

There is also a lack of focus on privacy (like newer Waterfox releases allowing various forms of prefetching for example) and an increasingly arrogant attitude of the developers, like taking away the ability of editing 000-waterfox.js (the Waterfox-specific preferences) from other contributors. No idea what practical purpose this even serves, as contributors can't directly patch the source code without approval anyway, so why aren't you open to suggestions? I don't get it. Anyway, if you think you need to manage this on your own, which is in principle fine by me, then at least you should be more responsive to requests like the request I made here just before this comment.

You also ignore longstanding issues like Waterfox acting up when connected to public WiFi hotspots in spite of me having brought this up numerous times(!) over the course of months(!), as if it's the intended behavior. Wow, I mean, if you give up on a more "hands on" development approach with greater community involvement, you better make sure to be more responsive to bug reports at least, otherwise this shows that you can NOT handle it without more direct community involvement.

I am frustrated with this software but more so the development process, I think I will throw my support behind LibreWolf in the future, their developers seem more sensible to me and follow more streamlined development processes. Highly annoyed by the ongoings here!

You can now hide or downvote or delete my post or whatever, I just feel like this needed to be said. I am pretty much done here if nothing changes for the better.

**Comment by adamp01** [comment]
Hey @Peacock365 - Apologies for the slow response, I've been doing a lot of infra work and haven't been actively monitoring things as much as I should.

I've done a PR to cover the additional preferences you mentioned above. We did unlock the captive portal pref for G5, but don't believe it should be true by default.

For Proton, you can set `userChrome.theme.enable` to false. This is a preference that we are still in the process of adding to `about:preferences` but that will be coming shortly.

The main reason that major releases have been challenging is related to the amount of updates that had historically been made to Mozilla controlled source code, so doing a huge rebase onto a new major branch had conflicts galore. We have been putting a lot of work in to untangling this, something that we have almost finished.

Why do you say that we have taken away the ability of editing 000-waterfox.js from contributors? Is this related to locking prefs or something else?

I, personally, have greatly appreciated your input since I've been working on the browser and apologise that delays in response and action have removed any desire for you to continue this. I wish I could say with certainty that moving forward everything (specifically major releases) will be far more efficient, but we are always at the mercy of Mozilla to some extent.
