### ISSUE TITLE
Download display issue

### ISSUE THREAD

**Issue by Skyapex** [MrAlex94/Waterfox#2918]
### What happened?

When downloading anything the download popup pops up but no downloads are being displayed! It just says "No downloads for this session".
![Screenshot 2022-12-04 011606](https://user-images.githubusercontent.com/91699407/205467714-6f5c84ba-6c3d-4df5-b889-57f1d1ab24fe.png)

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by 8bitDingo** [comment]
Also experiencing this issue for the last few days also on Ubuntu up to date patched OS. Issue persists in safe mode Waterfox launch. Suspect an OS patch.

OS: Linux 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
WaterFox: WaterfoxLimited Waterfox G5.1 20221114141453 20221114141453

recent updates included upgraded linux firmware.

e.g.:
Upgrade: linux-headers-generic:amd64 (5.15.0.53.53, 5.15.0.56.54), linux-image-generic-hwe-22.04:amd64 (5.15.0.53.53, 5.15.0.56.54), linux-generi
c:amd64 (5.15.0.53.53, 5.15.0.56.54), linux-headers-generic-hwe-22.04:amd64 (5.15.0.53.53, 5.15.0.56.54), linux-generic-hwe-22.04:amd64 (5.15.0.5
3.53, 5.15.0.56.54), linux-image-generic:amd64 (5.15.0.53.53, 5.15.0.56.54)

**Comment by 8bitDingo** [comment]
It just started working again today/resolved.

The only change on the machine appears to be the following ubuntu patch:

-- 
Start-Date: 2022-12-06  06:29:53
Commandline: apt-get upgrade
Upgrade: libbpf0:amd64 (1:0.5.0-1, 1:0.5.0-1ubuntu22.04.1), libxml2:amd64 (2.9.13+dfsg-1ubuntu0.1, 2.9.13+dfsg-1ubuntu0.2), ca-certificates:amd64 (20211016, 20211016ubuntu0.22.04.1)
End-Date: 2022-12-06  06:29:55
--

**Comment by 8bitDingo** [comment]
Did the Ubuntu upgrade and the issue has returned. Puzzling.

Ubuntu 22.10 x86_64
DE: GNOME
WM: Mutter
WM Theme: Adwaita
Theme: Yaru-dark

WaterfoxLimited Waterfox G5.1 20221114141453 20221114141453

**Comment by 8bitDingo** [comment]
Weird. It is working again after this:  Upgrade: xserver-xorg-core:amd64 (2:21.1.4-2ubuntu1.2, 2:21.1.4-2ubuntu1.3), xserver-xorg-legacy:amd64 (2:21.1.4-2ubuntu1.2, 2:21.1.4-2ubuntu1.3), xserver-common:amd64 (2:21.1.4-2ubuntu1.2, 2:21.1.4-2ubuntu1.3), xwayland:amd64 (2:22.1.3-2ubuntu0.1, 2:22.1.3-2ubuntu0.2), xserver-xephyr:amd64 (2:21.1.4-2ubuntu1.2, 2:21.1.4-2ubuntu1.3)

I give up. Can't reproduce the issue reliably or see a pattern.

**Comment by a0eoc** [comment]
I've seen this behavior but only when containers were used. At least all downloads were available in `about:downloads`.

**Comment by SkylordBrebro** [comment]
I am also having this issue on windows.

**Comment by ASlimguy** [comment]
Same problem here - Waterfox G5.1.1 does not show download display, either during or after a download.  Download directory on HD is correct.  Files DO download.  Win10 Professional.

**Comment by feelingwalnut** [comment]
sounds like a duplicate of https://github.com/WaterfoxCo/Waterfox/issues/2882

tl:dr solution may be the final comment over there.

**Comment by Skyapex** [comment]
![image](https://user-images.githubusercontent.com/91699407/217963134-c5b426ae-5ed7-4fb5-ad38-c9e98c3d858f.png)
Well.. seems it has been fixed now.

**Comment by feelingwalnut** [comment]
> ![image](https://user-images.githubusercontent.com/91699407/217963134-c5b426ae-5ed7-4fb5-ad38-c9e98c3d858f.png) Well.. seems it has been fixed now.

open your browser, make the tab private, browse to a site and download. it should be blank.
close your browser
open your browser, browse to a website and download, see if it has reverted to default behavior or is masking the download as if it were still private.

mine is still demonstrating the bug. waterfox 5.1.2 linux

to undo the bug, toggle to a private tab, toggle back to normal, close and reopen browser, visit website and it should function as intended.

to avoid the bug, whenever using a private tab, ensure you dont close browser while in a private tab,

**Comment by SwooshyCueb** [comment]
Still happens in G5.1.10 on KDE Neon

**Comment by feelingwalnut** [comment]
> Still happens in G5.1.10 on KDE Neon

still present on debian G5.1.10
resolution is still the same as previously posted.

merge #2987 ?
i'm not intimatly familiar with github but there are many recent commits to the code which i believe is relevant to this issue.

**Comment by gulkily** [comment]
I'm still having this issue on Mac.

Waterfox: G6.0.19 (64-bit)
Mac: 10.15.7

**Comment by UmiAkai** [comment]
I have this same issue recently with G6.0.19 on win11
I tried downgrade all the way to 6.0 and up to 6.5.0b it's all the same.
No issue on my win10 laptop
Make a new profile and this problem is gone, but I can't just delete my old profile. There must be one setting in the profile files make this problem, but "Remember browsing and download history" is checked.
