### ISSUE TITLE
Abnormal RAM usage

### ISSUE THREAD

**Issue by SnowCutieOwO** [MrAlex94/Waterfox#3082]
### What happened?

A bug happened!
English:
Seems that WaterFox have some small problems on handling RAM usage.
When I opened a website and leave it for an hour, when I back it's sleeping, but with a huge memory.
(This page is not showing on screen)
After I opened this page it becomes normal again.
Chinese (Simplified):
WaterFox 似乎在内存占用上有一些问题。
我打开了一个页面并让它保持开启了一个小时，当我回来的时候它处于休眠状态，有着非常大的内存占用。
（打开的页面是最小化状态的）
直到我再次浏览这个页面时，内存占用才逐渐正常。

Extra:
WaterFox sometimes have some spikes on memory usage, if any extra information is required, I'm happy to provide.
WaterFox 有些时候占用不很稳定，如果需要提供任何的额外信息，我很乐意。

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G5

### What platform are you seeing the problem on?

Windows

**Comment by R3DIANCE** [comment]
![kdhvmpkmBS](https://github.com/BrowserWorks/Waterfox/assets/13523121/ce095992-e722-4772-bb6a-fab02a26a416)
![LghbxJYBMM](https://github.com/BrowserWorks/Waterfox/assets/13523121/8a4ddd0e-9851-43af-adde-cbbc11625eda)

This happens when randomly watching/pausing youtube videos.
Edition:	Windows 11 Pro
Version:	23H2
OS build:	22631.3447

Waterfox Version: G6.0.13 (64-bit)

**Comment by MrAlex94** [comment]
Did this happen with G6.0.12?

Thanks for reporting this, it's very helpful!

**Comment by SnowCutieOwO** [comment]
> Did this happen with G6.0.12?
> 
> Thanks for reporting this, it's very helpful!

No. But another kind of high usage came.
It will occur randomly and gone quickly, I couldn't figure out any other things that noticeable.

**Comment by MrAlex94** [comment]
> I couldn't figure out any other things that noticeable.

If you manage to find a way to reproduce reliably, would be of great help! I've tried some test environments with lots of tabs + youtube videos in the background, but no luck yet.

**Comment by piroor** [comment]
All reporters seeing this kind issue including @SnowCutieOwO: `about:memory` information may help investigating memory leak. Could you try these steps?:

1. Confirm Waterfox leaks RAM.
2. Go to `about:memory` (from the address bar).
3. Click "Minimize memory usage" button and wait for a while.
4. After compaction is finished, see the task manager. If the RAM usage is not reduced (or increased again), see the next step.
5. In `about:memory`, uncheck `anonymize`  in the top box labeled as `Save memory reports`.
6. Click `Measure and save...` button in the top box.
7. You'll get a report file `memory-report.json.gz`. It contains full URLs you are opening in Waterfox, so you should not upload it to any public place (like this issue tracker) instead I recommend you to send it as an attachment of an email to @MrAlex94 (or me `piro.outsider.reflex@gmail.com` if you can trust me).

**Comment by SnowCutieOwO** [comment]
> All reporters seeing this kind issue including @SnowCutieOwO: `about:memory` information may help investigating memory leak. Could you try these steps?:
> 
>     1. Confirm Waterfox leaks RAM.
> 
>     2. Go to `about:memory` (from the address bar).
> 
>     3. Click "Minimize memory usage" button and wait for a while.
> 
>     4. After compaction is finished, see the task manager. If the RAM usage is not reduced (or increased again), see the next step.
> 
>     5. In `about:memory`, uncheck `anonymize`  in the top box labeled as `Save memory reports`.
> 
>     6. Click `Measure and save...` button in the top box.
> 
>     7. You'll get a report file `memory-report.json.gz`. It contains full URLs you are opening in Waterfox, so you should not upload it to any public place (like this issue tracker) instead I recommend you to send it as an attachment of an email to @MrAlex94 (or me `piro.outsider.reflex@gmail.com` if you can trust me).

After the step 3, the usage sharply increased for about a second.
And `anonymize` check box is already unchecked when I opened this page.
Done, I've sent the email to you, hope it'll work.

By the way, the occasion when RAM are high is pretty rare in contrast to previous version. :/

**Comment by piroor** [comment]
@SnowCutieOwO Thanks! I've seen your memory usage and it says that top 6 memory eaters are:

* about 360MB for the main process
* about 170MB for the website1
* about 190MB for the extensions process (including Waterfox Sidebar)
* about 120MB for the website2
* about 120MB for the website3
* about 40MB for the GPU process

And this memory report says more:

* Resources of Waterfox Sidebar directly use 0.4MB in the main process and 24MB in the extensions process. This is not so large.
* On the other hand, 10MB in the main profile and 13MB in the extensions process are used for very large strings.
  * A 4MB string in the extensions process is a very large user script. This looks to be unrelated to Waterfox Sidebar.
  * In the main process, there are many base64 encoded PNG images or scripts. I guess these images are thumbnails or favicons.

I have one question: does the RAM usage of the extensions process continuously increase over 190MB? If so a performance profile may help our more investigation. Steps to collect a performance profile:

1. Confirm that the RAM usage is continuously increasing.
2. Open the web developer tools. (The keyboard shortcut is F12.)
3. Go to the settings page of the developer tools. (The keyboard shortcut is F1.)
4. Turn checkboxes "Enable browser chrome and add-on debugging toolboxes" and "Enable remote debugging" on.
5. Open the "borwser toolbox". (The humberger menu => More Tools => Browser Toolbox)
6. A confirmation dialog with the title "Incoming Connection" appears, so click "OK".
7. In the browser toolbox, click the "Performance" tab.
8. Choose "Waterfox" in the "Settings" dropdown menu.
9. Click the "Start recording" button.
10. Wait 10 seconds or wait for a while until the RAM usage is increased enough, ex. 200MB.
11. Click the "Capture recording" button.
12. Wait for a while until a new browser window is opened with URL like `https://profiler.firefox.com/from-browser/calltree/?globalTrackOrder=...`.
13. Click "Upload Local Profile" in the top bar.
14. A popup appears.
15. Turn all checkboxes on, and click the "Download" button.
16. Send the saved file to us.

**Comment by SnowCutieOwO** [comment]
&nbsp;

Message ID: ***@***.***&gt;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BrowserWorks/Waterfox"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月8日(星期三) 凌晨0:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BrowserWorks/Waterfox] Abnormal RAM usage (Issue #3082)

**Comment by SnowCutieOwO** [comment]
&nbsp;

Message ID: ***@***.***


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "BrowserWorks/Waterfox"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月8日(星期三) 凌晨0:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BrowserWorks/Waterfox] Abnormal RAM usage (Issue #3082)


 Um it lasts only a few second, and since the time is long I couldn't redo the circumstance that time. After all thanks for your reply and detailed instructions!

**Comment by Tampa** [comment]
So I can usually force this to happen with heavy youtube browsing. Worst case it fills up memory completely and locks the entire OS up.

The worst I have seen regarding this was an infinite loop on youtube just constantly reloading the page. This is somewhat fixed by updating the ublock filters, but I still get the random page reload as the page fails to load anything but the video itself. So my guess is the constant reloading is still happening in the background causing the memory to explode and that some plugin might be partly responsible for it. Given how many I have though it's hard to say if it is just ublock or another plugin also messing with things.

It doesn't happen all the time, but the longer I have the youtube tab open the worse it gets throughout the day. Maybe it's wise to introduce a max_memory_per_tab setting and crash the tab if it reaches that? I know, that'd just be a bandaid for the larger issue, but it would prevent hard crashes and make it a bit easier to spot this without constantly monitoring memory usage. Can always be disabled for those that need it as well.

This is a youtube tab load and video load from the console perspective. The video player loaded, but the page reloaded as it failed to load the contents of description etc.
https://pastebin.com/q3DfKGi6

I'll give this a workout and see if I can't break this further.

Edit: Okay I have something here. Something that I suspected happening before. Two tabs open. One on youtube, the other on lieferando and watching taskmanager. Memory goes up by 100mb every second, reaches 4-5gb then GC kicks in it seems. So if that GC fails this would just run away on itself. I'm doing some measure and save while this is going on.

**Comment by MrAlex94** [comment]
@Tampa could you disable the sidebar by setting `browser.sidebar.disabled` to true in about:config? This way we can see if it's related or not. See if you can reproduce.

**Comment by Tampa** [comment]
So instantly the pages load faster, that's quite obvious. So far no large memory leaks with the original reproduction method I had. Memory staying a lot lower overall. I'll keep trying and monitor some more tomorrow. Wouldn't say it's 100% related yet, but certainly seems to make a positive impact on performance and memory.

**Comment by Tampa** [comment]
Have not been able to reproduce the total runaway memory condition, but have seen some strange behavior still.

https://i.imgur.com/hdyoXZp.gif

You can see periodically the memory usage goes up by 100mb per second until gc kicks in and clears it. I tried to capture a few memory reports during those times. Not sure if that's normal behavior, but I fear that should gc be delayed or not run for whatever reason that would blow up.

Youtube itself still does the whole reloading dance once in a while. Some videos work fine others it just loads part of the page and then the whole thing reloads. Over the course say 10 of leaving the tab open it does slow down and eventually the tab becomes very sluggish. Usually closing it and opening a new one 5 minutes later helps for a bit.

It has not catastrophically blown up for 2 days, but I'll keep monitoring. Usually this issue showed up once a week. After the sidebar change the reproduction steps no longer result in the same amount of memory, so it did something good. The reloading tab thing I'm pretty sure is something with ublock and youtube fighting each other, though it seems Firefox itself doesn't have that much trouble with it, so my best guess would be some additional privacy or security things also messing with things. Hope this helps, let me know if more information is needed :)

**Comment by IanKemp** [comment]
Just encountered what I believe is the same issue:

![image](https://github.com/BrowserWorks/Waterfox/assets/1726434/c51ca6fb-2050-4af3-ba23-742f2b651960)

Yes, that is a single tab using nearly **one hundred and twenty eight GIGABYTES** of memory - on a machine that has 64GB RAM. I was wondering why I was experiencing system crashes recently, I thought it was due to bad drivers, but it seems that the culprit is Waterfox - it fills up all my RAM, then the disk runs out of space because the swap file fills up, and Windows 11 can't allocate any more memory, so it just dies.

I didn't get a chance to check `about:memory` because I killed the above process to stop it bringing my machine down (again), but I am 99.99% certain it's due to YouTube music playlists. I listen to ~1hr long synthwave/chillwave music on YT, then when that video is finished I click through to the next one that YT recommends, and repeat this throughout my workday - and I heard the music skip when I killed that process.

I will keep an eye on this and report if I'm able to capture traces from `about:memory` as per [this comment](https://github.com/BrowserWorks/Waterfox/issues/3082#issuecomment-2098385819).

> Maybe it's wise to introduce a max_memory_per_tab setting and crash the tab if it reaches that?

I second this, especially given that I am now the second person to report this runaway memory consumption that is literally causing the machine to crash.

**Comment by piroor** [comment]
After some more research I've found an infinite loop containing canvas rendering triggered by Waterfox Sidebar's in-tab previews. It has been fixed at TST https://github.com/piroor/treestyletab/commit/16754e5166116241f1d97cae79c9d6bae0107df3 and I've pushed same fix to Waterfox Sidebar. There still be no evidence but I think it could affect this increased RAM usage problem.

**Comment by johnwcchau** [comment]
I had same situation and disabling sidebar in about:config (browser.sidebar.disabled=true) workaround-ed this issue

**Comment by MrAlex94** [comment]
Hi all,

G6.0.15 is out now: https://www.waterfox.net/download/

If you could test and see if that resolves the issues, which I believe it should, we should be groovy!

**Comment by Tampa** [comment]
So after this upgrade we should enable the sidebar again I assume? I'll do that and re-run tests, will edit if I find something.

EDIT: After enabling sidebar again I am seeing no massive increases in memory anymore with my usual test case, but over time memory does add up. About 200mb per hour in my case. So there is definitely small leak somewhere or things accumulating over time, but that's not as serious as previously. Will keep monitoring and edit if I find a new test case for memory explosion.

**Comment by IanKemp** [comment]
Just restarted Waterfox to upgrade to G6.0.15 and have a process using over 50GB:

![image](https://github.com/BrowserWorks/Waterfox/assets/1726434/29bc91ec-0a0b-4abe-afa2-5ae85460e978)

According to `about:memory` the culprit appears to be extensions-related:

![image](https://github.com/BrowserWorks/Waterfox/assets/1726434/6a9aa053-96f5-4524-90a6-488b01b4ae62)

Digging deeper:

![image](https://github.com/BrowserWorks/Waterfox/assets/1726434/4fedec75-56ad-498f-9d92-abff21b36b70)

So _something_ in extensions is allocating _all the strings_.

I followed the instructions provided by @piroor to capture a memory profile, I also captured a snapshot from `about:memory`, @MrAlex94 please advise where I should send these.

**Comment by MrAlex94** [comment]
> I followed the instructions provided by @piroor to capture a memory profile, I also captured a snapshot from `about:memory`, @MrAlex94 please advise where I should send these.

Sorry, completely missed this! You can shoot it over to tiny.hope0375@fastmail.com

**Comment by IanKemp** [comment]
> > I followed the instructions provided by @piroor to capture a memory profile, I also captured a snapshot from `about:memory`, @MrAlex94 please advise where I should send these.
> 
> Sorry, completely missed this! You can shoot it over to [tiny.hope0375@fastmail.com](mailto:tiny.hope0375@fastmail.com)

Sent!
